name: Story point correction reminder

# This workflow reminds writers to populate the Story point correction field after they close an issue.

on:
  issues:
    types: [closed]
permissions: 
  issues: write
jobs:
  comment_when_closed:
    runs-on: ubuntu-latest
    steps: 
      - name: Check if this issue is assigned to a member of the docs team
        uses: actions/github-script@626af12fe9a53dc2972b48385e7fe7dec79145c9
        id: assigned-to-member
        with:
          github-token: ${{ secrets.GHACTIONS_TESTING }}
          result-encoding: string
          script: |
            const issue_assignee = context.payload.issue.assignee
            const teamMembers = await github.request(
              `/orgs/github/teams/docs/members?per_page=100`
            )
            const logins = teamMembers.data.map(member => member.login)
            if (logins.includes(issue_assignee)) {
              console.log(`This issue is assigned to ${issue_assignee} (on the docs team).`)
              return 'true'
            }
            console.log(`This workflow was triggered by ${issue_assignee} (not on the docs team), so no action will be taken.`)
            return 'false'
            
      - name: Exit if not triggered by a docs team member
        if: steps.assigned-to-member.outputs.result == 'false'
        run: |
          echo Aborting. This workflow only runs on issues assigned to a member of the docs team.
          exit 1
          
      - name: Comment on relevant issues
        if: |
          github.event.issue.assignee.login && 
          !contains(github.event.issue.labels.*.name, 'duplicate') && 
          !contains(github.event.issue.labels.*.name, 'enhancement')
        run: gh issue comment $ISSUE --body "👋 Hi @$ASSIGNEE, it looks like you closed this issue. Don't forget to populate the **Story point correction** field for the focus team project!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
          ASSIGNEE: ${{ github.event.issue.assignee.login }}
        
          
