name: Reusable workflow test

on: 
  workflow_call:
    inputs:
       context-test:
        description: 'Testing using inputs context here.'
        required: false
        default: '${{ inputs.test-value }}-test'
        type: string

jobs:
  print-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print stuff
        run: echo ${{ inputs.context-test }} hopefully works
      
