name: Test ternary operator on issue labels
on:
  issues:
    types: [reopened, opened]

permissions:
    issues: write
    contents: read

jobs:
  find-labels:
    runs-on: ubuntu-latest
    steps:

    - name: Test operator
      env:
        CONTAINS_LABEL: ${{ (contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'question')) && 'Issue IS labeled' || 'Issue NOT labeled' }}
      run: echo $CONTAINS_LABEL
